# Generated by Django 3.2.25 on 2024-06-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20240607_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='street',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='zip_code',
        ),
    ]
